# Python library

- Python library is the collecton of function and methods that allow us perform  many action without writing the code.
- like
    - Numpy
    - Pandas
    - Matplotlib.pypolt
    - Seaborn

# Numpy Packages
- Numpy stands for **Numeric Python** and is the core library for numeric and scientific computing.
- It consists multi-dimenssional array object and collection of routiness  for processing those array
- Numpy work with with arry

In [1]:
# importing numpy packages
import numpy as np

In [2]:
#creating a list
l1=[2,3,4,5,6]

In [3]:
#converting ist into array
x=np.array(l1)
print(x)

[2 3 4 5 6]


In [4]:
#checking shape of array
x.shape

(5,)

In [5]:
#checking dimenssional of array 
x.ndim

1

In [6]:
#creating another list
l2=[3,4,6,8,9]

In [7]:
#Adding l1 and l2 list
l1+l2

# In output list cincatinate with each each other won't permorm additon

[2, 3, 4, 5, 6, 3, 4, 6, 8, 9]

In [8]:
#convert l2 in array
y=np.array(l2)
print(l2)

[3, 4, 6, 8, 9]


In [9]:
# adding x & y array during calculation on array element sould be same in each data structures.

z=x+y
print(x)


[2 3 4 5 6]


In [203]:
x

array(['23', '23.5', 'vineet', 'True'], dtype='<U32')

In [204]:
x.ndim

1

In [208]:
#making 2D array 
q=np.array(x,ndmin=2)
q

array([['23', '23.5', 'vineet', 'True']], dtype='<U32')

In [207]:
q.ndim

2

In [215]:
#changing data type in array

p=np.array([10,20,30,40],dtype=str)

In [216]:
p

array(['10', '20', '30', '40'], dtype='<U2')

# 1D Numpy Array

In [10]:
# creatig one dimenssional array

ages=np.array([22,34,23,45,56,63])
ages

array([22, 34, 23, 45, 56, 63])

In [11]:
# checking dimenssional 

ages.ndim

1

In [12]:
ages.shape

(6,)

In [37]:
type(ages)

numpy.ndarray

**Accessing array**

In [13]:
ages[0]

22

In [14]:
ages[-1]

63

In [15]:
ages[0:3]

array([22, 34, 23])

In [16]:
#accessing using condition

ages[ages>=34]

array([34, 45, 56, 63])

## changing data type through heirarchy(str,float,int,bool)

In [17]:
# changed every element in string

x=np.array([23,23.5,"vineet",True])
print(x)

['23' '23.5' 'vineet' 'True']


In [18]:
#float
y=np.array([23,23.5,True])
print(y)

[23.  23.5  1. ]


In [19]:
#integr

z=np.array([23,True])
print(z)

[23  1]


# 2D Numpy Array

In [55]:
#creating 2 dimenssional array

runs=np.array([
    [23,44],
    [45,67],
    [25,80],
    [70,35]
])

In [56]:
runs

array([[23, 44],
       [45, 67],
       [25, 80],
       [70, 35]])

In [22]:
runs.ndim

2

In [23]:
runs.shape

(4, 2)

In [38]:
type(runs)

numpy.ndarray

### Accessing Array

In [24]:
#subsetting

runs[2,1]

80

In [25]:
runs[3,0]

70

In [26]:
runs[3,1]

35

In [27]:
#slicing
runs[1:,1]

array([67, 80, 35])

In [28]:
runs[2:,0]

array([25, 70])

In [29]:
runs[2:,:]

array([[25, 80],
       [70, 35]])

In [30]:
# using condition

runs[runs>50]

array([67, 80, 70])

# Numpy Operators
- when we have two condition in array we use following operators.
   - np.logical_and()
   - np.logical_or()
   - np.logical_not()

In [51]:
a=runs[np.logical_and(runs>40,runs<70)]
a

array([44, 45, 67])

In [52]:
b=runs[np.logical_or(runs>40,runs<70)]
b

array([44, 45, 67])

In [53]:
c=runs[np.logical_not(runs>40,runs<70)]
c

array([], dtype=int32)

# reshaping arrray

In [39]:
ages

array([22, 34, 23, 45, 56, 63])

In [40]:
ages.shape


(6,)

In [45]:
#converting 1D array into 2D array
ages.shape=(3,2)

In [42]:
ages

array([[22, 34],
       [23, 45],
       [56, 63]])

In [43]:
ages.shape

(3, 2)

In [44]:
ages.ndim

2

In [57]:
runs

array([[23, 44],
       [45, 67],
       [25, 80],
       [70, 35]])

In [58]:
runs.shape

(4, 2)

In [59]:
runs.ndim

2

In [62]:
#converting 2D array into 1D arrray

runs.shape=(8,1)

In [63]:
runs

array([[23],
       [44],
       [45],
       [67],
       [25],
       [80],
       [70],
       [35]])

In [64]:
runs.shape

(8, 1)

In [65]:
runs.ndim

2

# Initializing Numpy with Zeros

In [70]:
n=np.zeros((1,2))
n

array([[0., 0.]])

In [72]:
n1=np.zeros((10,10))
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Initializing with same number

In [78]:
n3=np.full((4,4,),99)
n3

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

# Initializing with in range

In [82]:
#To getting range number between to numbers
n5=np.arange(1,10)
n5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
#To getting inervels in range
n6=np.arange(1,10,2)
n6

array([1, 3, 5, 7, 9])

In [217]:
# Initializing with random number
n7=np.random.randint(1,100,11)

In [218]:
n7

array([24,  3, 22, 53,  2, 88, 30, 38,  2, 64, 60])

To getting Same random number use seed


In [112]:
np.random.seed(42)
np.random.randint(1,100,11) # we will get same random number

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88])

# Joining Numpy array
- vstack()
- hstack()
- column_stack()

In [130]:
#creating two array
a1=np.array([10,23,45,50,60])
a2=np.array([20,30,40,60,70])

### 1. vstack()

In [131]:
v1=np.vstack((a1,a2))
v1

array([[10, 23, 45, 50, 60],
       [20, 30, 40, 60, 70]])

In [132]:
v1.shape

(2, 5)

In [133]:
v1.ndim

2

### 2. hstack()


In [134]:
h=np.hstack((a1,a2))
h

array([10, 23, 45, 50, 60, 20, 30, 40, 60, 70])

In [135]:
h.shape

(10,)

In [127]:
h.ndim

1

### 3. column_stack()

In [137]:
cs=np.column_stack((a1,a2))
cs

array([[10, 20],
       [23, 30],
       [45, 40],
       [50, 60],
       [60, 70]])

In [138]:
cs.shape

(5, 2)

In [139]:
cs.ndim

2

## Numpy other Operation (Intersection,Union and difference)


In [149]:
a1

array([10, 23, 45, 50, 60])

In [150]:
a2

array([20, 30, 40, 60, 70])

In [146]:
#Intersection -->To getting comman value from array
np.intersect1d(a1,a2)

array([60])

In [145]:
#Union--->TO getting all value with repeating value
np.union1d(a1,a2)

array([10, 20, 23, 30, 40, 45, 50, 60, 70])

In [147]:
#To get unique value from a1 array after subtract comman value

np.setdiff1d(a1,a2)

array([10, 23, 45, 50])

In [148]:
#To get unique value from a2 array after subtract comman values
np.setdiff1d(a2,a1)

array([20, 30, 40, 70])

# Mathimatics operation on Numpy Array

## 1. Adition of Numpy Array

In [151]:
a1

array([10, 23, 45, 50, 60])

In [152]:
a2

array([20, 30, 40, 60, 70])

In [159]:
np.sum(a1)

188

In [160]:
np.sum(a1)

188

In [167]:
np.sum([a1,a2])

408

In [163]:
#column wise sum
np.sum([a1,a2],axis=0)

array([ 30,  53,  85, 110, 130])

In [156]:
#Row wise sum
np.sum([a1,a2],axis=1)

array([188, 220])

## 2. for subtraction in array

In [175]:
np.subtract(a2,a1)

array([10,  7, -5, 10, 10])

## 3. For multiply  in arrays

In [171]:
np.multiply(a1,a2)

array([ 200,  690, 1800, 3000, 4200])

## 4. for division in  array

In [173]:
np.divide(a2,a1)

array([2.        , 1.30434783, 0.88888889, 1.2       , 1.16666667])

# Numpy array mathimatics

In [180]:
a=np.array([10,20,30,40,50,60])
a

array([10, 20, 30, 40, 50, 60])

In [182]:
#basic addition
a1=a+2
a1

array([12, 22, 32, 42, 52, 62])

In [183]:
# basic subtraction
a2=a-2
a2

array([ 8, 18, 28, 38, 48, 58])

In [184]:
# basic multiplicaton
a3=a*2
a3

array([ 20,  40,  60,  80, 100, 120])

In [185]:
#basic division
a4=a/2
a4

array([ 5., 10., 15., 20., 25., 30.])

# Numpy Statistics Function

1. mean()

In [186]:
a

array([10, 20, 30, 40, 50, 60])

In [187]:
np.mean(a)

35.0

2. median()

In [188]:
np.median(a)

35.0

3. Standard deviation/std()

In [189]:
np.std(a)

17.07825127659933

In [ ]:
# second method

In [192]:
b=np.var(a)
b

291.6666666666667

In [198]:
std=np.sqrt(b)
std

17.07825127659933

# Numpy Save & Load

In [199]:
a


array([10, 20, 30, 40, 50, 60])

In [200]:
np.save("numpy_file",a)

In [201]:
np.load("numpy_file.npy")

array([10, 20, 30, 40, 50, 60])